### PR TITLE
Added ability to specify integrity and crossorigin properties on CSS and JS resources

### PR DESCRIPTION
**Pull request by Blackbaud-PaulCrowder**
#43

### CODE REVIEW

**Comment by Blackbaud-PaulCrowder** [comment]
Just checking in again to see if you guys could pull this in soon.

**Comment by sgarbesi** [comment]
@Blackbaud-PaulCrowder Haven't forgot about this. The changes look a bit radical for v1 and should be for v2. I'll give an answer tomorrow. Sorry, been extremely busy.

**Comment by Blackbaud-PaulCrowder** [comment]
OK, thanks.  The changes really come down to overloading each property to allow an object in addition to the array and string types that were already supported.  This also opens up the option to specify more properties on a given library so features like this can be added in the future.

**Comment by Blackbaud-PaulCrowder** [comment]
Just thought I'd check back and see if there's a possibility this will get merged in.

**Comment by danimalquackers** [comment]
This feature would be extremely useful for me and is one of the only reasons I'm considering holding back on using Fallback. Is there an update as to whether this will get merged in? I want to know if I should use fallback, but that really depends on whether SRI will be supported.

**Review by danimalquackers — CHANGES_REQUESTED** [review]
There is one feature I think would be useful to add: make the integrity property support an array (which is then joined by whitespace and put in the integrity tag, according to the spec at https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity, which mentions multiple hashes can be used.
This would also be useful because files vary slightly from CDN to CDN.

**Comment by LaurentGoderre** [comment]
I also would like to get this in ASAP!

**Comment by LaurentGoderre** [comment]
@ Blackbaud-PaulCrowder I would like to propose a change in the way this is handled in order to avoid a change in configuration. We could keep integrities in the second object instead like so:

```js
fallback.load({
    jQuery: [
        '//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js',
        '/jquery/jquery.min.js'
    ],
    myApp: [
        '//cdn.io/myapp/v1/app.min.js',
        '/myapp/app.min.js',
    ]
}, {
    shim: {
        'myApp': ['jQuery']
    },
    integrities: {
        'jQuery': 'sha384-...'
    },
    callback: function() {}
});
```

**Comment by Blackbaud-PaulCrowder** [comment]
I'm fine with that, though it doesn't look like this is going to be merged.  You might just want to fork and make that change for yourself.

**Comment by LaurentGoderre** [comment]
Are you sure? This is way less radical of a change this way so I'm hoping that @sgarbesi would be open to the change in v1

**Comment by LaurentGoderre** [comment]
@sgarbesi what do you think about my proposal?

**Comment by sgarbesi** [comment]
@LaurentGoderre I'll try to look at this, this week. I've been reluctant to making changes since the library has been stable. If it's minimal, I'll merge it.

**Comment by LaurentGoderre** [comment]
@sgarbesi I haven't done the code yet, I just have example of what the config would look like so that it doesn't change the API. If you are ok with it I will create the PR

**Comment by sgarbesi** [comment]
@LaurentGoderre Make a PR.

**Pull request merged**
