### PR TITLE
Fix browser compatibility problems

### PR DESCRIPTION
**Pull request by markstos**
This updates the example to support IE < 9 by using jquery 1.10.x instead of 2.x, and fixes the <script> tag by putting it inside the <body> tag.

### CODE REVIEW

**Comment by markstos** [comment]
Looking at example.html with the IE 9 network inspector, I see two significant problems:
1. After the initial initial failure, the requests stop. The second valid URL is not attempted.
2. After removing the invalid jQuery reference, I can see that IE fetches the valid jQuery URL, but no attempts are made to fetch any version of jQuery URI that I see in that report. 

So far, I have not been able to get any diagnostics to appear in the IE JavaScript console to point me closer to the problem. 

Considering that we need to support at least IE 8, we'll have to evaluate whether to continue attempting to debug fallback.js further, or pursue an alternate solution. 

Have you referenced how the fallback code in require.js works? It claims to be compatible with IE 6+.

**Comment by sgarbesi** [comment]
No I haven't had time to take a peak, but I'd imagine their integrating the `onreadystatechange` event.

I'll take a peak later on tonight.

**Comment by sgarbesi** [comment]
Grab the latest revision 0.2.

It's now working for me in the latest versions of Google Chrome, Firefox and Safari.
...and IE 7, 8, 9 and 10.

Please confirm on your end.

**Comment by markstos** [comment]
I have confirmed it works-for-me in IE 7,8,9,10, Chrome and Firefox 14. Closing.

**Pull request closed without merging**
