### PR TITLE
add an initial bower.json file

### PR DESCRIPTION
**Pull request by displague**
If you register with bower, folks using Yeoman / Yo ( http://yeoman.io ) and Bower ( http://bower.io ) will have an easier time including your package in their client side requirements.

### CODE REVIEW

**Comment by sgarbesi** [comment]
@markstos is correct. I'm going to wait until I get the site + documentation up before moving forward with this.

**Comment by colthreepv** [comment]
+1 on this, i found this library really what i was looking for. :+1: 

i included in my current project using:

``` json
"dependencies": {
  "fallback.io": "git://github.com/dolox/fallback.js.git"
}
```

**Comment by sgarbesi** [comment]
@mrgamer Thanks for the feedback.

Launching the website soon and going to try and get it in bower as well.

**Comment by sgarbesi** [comment]
Added to bower.

@displague @markstos @mrgamer Thanks for the feedback and support guys!

bower search fallback
Search results:
    angular-svg-fallback git://github.com/qloo/angular-svg-fallback.git
    fallback git://github.com/dolox/fallback.git

**Pull request closed without merging**
